costmap_generator_node:
  ros__parameters:
    resolution: 0.05
    map_bounds:
      min_x: -6.0
      max_x: 6.0
      min_y: -6.5
      max_y: 6.5
    inflation:
      robot_radius: 0.35
      margin: 0.4
    costs:
      wall: 120
      partition: 120
      obstacle: 254
      default_cost: 254