path_planner_node:
  ros__parameters:
    map_configs:
      map_frame: "map"
      base_frame: "base_link"
    snapp_config:
      start_snap_radius: 0.3 #[m]
    a_star:
      plannning_cost: 3.0 #小さいほどギリギリの経路
    bspline:
      simplification_tolerance: 0.1 #DRP方で使う許容誤差率。これ以上離れている点は残す
      turning_angle_threshold: 15.0 #点群をbsplineで残す時どれくらいの角度以上だったら残す点群として扱うか
      samples_per_segment: 30 #滑らかさの制御（大きいほどなめらか）
      smoothness_weight: 1.0 #大きいほど中点へ強く寄せる
      control_point_step: 0.05 #[m] 1回の移動量の基準
      smoothing_iterations: 10 #平滑化の反復回数
